///stat_restore(player)
global.s_hp[argument0]                 =   global.s_hp[5]             
global.s_pp[argument0]                 =   global.s_pp[5]             
global.s_hpmax[argument0]              =   global.s_hpmax[5]          
global.s_ppmax[argument0]              =   global.s_ppmax[5]          
global.s_baseoff[argument0]            =   global.s_baseoff[5]        
global.s_basedef[argument0]            =   global.s_basedef[5]        
global.s_baseguts[argument0]           =   global.s_baseguts[5]       
global.s_basespeed[argument0]          =   global.s_basespeed[5]      
global.s_baseiq[argument0]             =   global.s_baseiq[5]         
global.s_off[argument0]                =   global.s_off[5]            
global.s_def[argument0]                =   global.s_def[5]            
global.s_luck[argument0]               =   global.s_luck[5]           
global.s_speed[argument0]              =   global.s_speed[5]          
global.s_guts[argument0]               =   global.s_guts[5]           
global.s_vitality[argument0]           =   global.s_vitality[5]       
global.s_iq[argument0]                 =   global.s_iq[5]             
global.s_guard[argument0]              =   global.s_guard[5]          
global.s_exp[argument0]                =   global.s_exp[5]            
global.s_level[argument0]              =   global.s_level[5]          
global.s_next[argument0]               =   global.s_next[5]           
global.weap_equip[argument0]           =   global.weap_equip[5]       
global.body_equip[argument0]           =   global.body_equip[5]       
global.arm_equip[argument0]            =   global.arm_equip[5]        
global.other_equip[argument0]          =   global.other_equip[5]      
global.s_name[argument0]               =   global.s_name[5]           
global.money                           =   global.money2              
global.money_saved                     =   global.money_saved2        

eqp_boosts(argument0)
